postgres_db_name = 'seta_test'
postgres_user = 'postgres'
postgres_pass = 'postgres'
host = 'db'
postgres_port = '5432'
secret_key = 'helololo-insecure-*&lqgwmli_pw+a*m+m0prxj@_+s1g9(1j8twzm5_^v4qqek#5-'
